/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

/**
 *
 * @author Hilmi, Faizah, dan Desta
 */
import javax.swing.JOptionPane;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.SQLException;
public class CekAir extends javax.swing.JFrame implements PerhitunganKesehatan{
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(CekAir.class.getName());

    /**
     * Creates new form CekAir
     */
    private double kebutuhanMl;
    private double kebutuhanAir;
    public CekAir() {
        initComponents();
        setResizable(false);
        setSize(1062, 574);
        setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblBerat = new javax.swing.JLabel();
        txtBerat = new javax.swing.JTextField();
        lblAktivitas = new javax.swing.JLabel();
        comAktivitas = new javax.swing.JComboBox<>();
        btnReset = new javax.swing.JButton();
        btnCek = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        lblHasil = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lblBerat.setFont(new java.awt.Font("SansSerif", 1, 24)); // NOI18N
        lblBerat.setText("Berat Badan (Kg)");
        getContentPane().add(lblBerat, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 190, 200, 30));

        txtBerat.setBackground(new java.awt.Color(204, 255, 255));
        txtBerat.setFont(new java.awt.Font("SansSerif", 1, 18)); // NOI18N
        getContentPane().add(txtBerat, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 230, 220, 60));

        lblAktivitas.setFont(new java.awt.Font("SansSerif", 1, 24)); // NOI18N
        lblAktivitas.setText("Aktivitas");
        getContentPane().add(lblAktivitas, new org.netbeans.lib.awtextra.AbsoluteConstraints(530, 190, 100, -1));

        comAktivitas.setBackground(new java.awt.Color(255, 255, 204));
        comAktivitas.setFont(new java.awt.Font("SansSerif", 0, 24)); // NOI18N
        comAktivitas.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Ringan", "Sedang", "Berat" }));
        getContentPane().add(comAktivitas, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 230, 250, 60));

        btnReset.setBackground(new java.awt.Color(204, 0, 51));
        btnReset.setFont(new java.awt.Font("SansSerif", 1, 16)); // NOI18N
        btnReset.setForeground(new java.awt.Color(255, 255, 255));
        btnReset.setText("Reset");
        btnReset.addActionListener(this::btnResetActionPerformed);
        getContentPane().add(btnReset, new org.netbeans.lib.awtextra.AbsoluteConstraints(780, 190, 150, 40));

        btnCek.setBackground(new java.awt.Color(0, 204, 51));
        btnCek.setFont(new java.awt.Font("SansSerif", 1, 16)); // NOI18N
        btnCek.setForeground(new java.awt.Color(255, 255, 255));
        btnCek.setText("Cek Sekarang");
        btnCek.addActionListener(this::btnCekActionPerformed);
        getContentPane().add(btnCek, new org.netbeans.lib.awtextra.AbsoluteConstraints(780, 250, 150, 40));

        jLabel4.setFont(new java.awt.Font("SansSerif", 1, 48)); // NOI18N
        jLabel4.setText("Cek Kebutuhan Air");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 20, 470, 80));

        lblHasil.setBackground(new java.awt.Color(204, 255, 204));
        lblHasil.setFont(new java.awt.Font("SansSerif", 0, 24)); // NOI18N
        lblHasil.setForeground(new java.awt.Color(255, 255, 255));
        lblHasil.setOpaque(true);
        getContentPane().add(lblHasil, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 330, 770, 160));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/background/bgAir1.png"))); // NOI18N
        jLabel1.setText("\n");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1060, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnResetActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnResetActionPerformed
        // TODO add your handling code here:
        txtBerat.setText("");
        comAktivitas.setSelectedIndex(0);
        lblHasil.setText("");
        lblHasil.setBackground(new java.awt.Color(240, 240, 240));
        txtBerat.requestFocus();
    }//GEN-LAST:event_btnResetActionPerformed

    private void btnCekActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCekActionPerformed
        // TODO add your handling code here:
        Connection conn = null;
        PreparedStatement pst = null;

        try {
            // 1. Ambil data dari input
            double berat = Double.parseDouble(txtBerat.getText().trim());
            String aktivitas = comAktivitas.getSelectedItem().toString();
  
            // Validasi angka
            if (berat <= 0) {
                JOptionPane.showMessageDialog(this, "Masukkan berat badan lebih dari 0!", "Input Salah", JOptionPane.WARNING_MESSAGE);
                return;
            }
          // 2. Hitung kebutuhan air (sesuai logika)
            if (aktivitas.equals("Ringan")) {
                kebutuhanMl = berat * 35;
            } else if (aktivitas.equals("Sedang")) {
                kebutuhanMl = berat * 40;
            } else {
                kebutuhanMl = berat * 45;
            }
            kebutuhanAir = kebutuhanMl;
            double kebutuhanLiter = kebutuhanMl / 1000;

            // 3. Tampilkan hasil di layar
            lblHasil.setText(String.format("<html>💧 Kebutuhan Air Harian Anda:<br>%.0f ml<br>≈ %.2f Liter</html>", kebutuhanMl, kebutuhanLiter));
             conn = Koneksi.bukaKoneksi();
            String sql = "INSERT INTO riwayat_air (id_pengguna, berat, aktivitas, kebutuhan_air) VALUES (?, ?, ?, ?)";
            pst = conn.prepareStatement(sql);

            pst.setInt(1, 1);                 // ID user sementara 1
            pst.setDouble(2, berat);
            pst.setString(3, aktivitas);
            pst.setDouble(4, kebutuhanMl);

            pst.executeUpdate();
            JOptionPane.showMessageDialog(this, "✅ Data berhasil disimpan ke Riwayat Air!");

        } catch (NumberFormatException e) {
            JOptionPane.showMessageDialog(this, "❌ Hanya masukkan angka untuk berat badan!", "Kesalahan Input", JOptionPane.WARNING_MESSAGE);
        } catch (SQLException e) {
            JOptionPane.showMessageDialog(this, "❌ Gagal simpan: " + e.getMessage(), "Kesalahan Database", JOptionPane.ERROR_MESSAGE);
        } finally {
            try {
                if (pst != null) pst.close();
                if (conn != null) conn.close();
            } catch (SQLException ex) {
                ex.printStackTrace();
            }
        }
    }//GEN-LAST:event_btnCekActionPerformed

    @Override
    public double hitungNilai() {
        return kebutuhanMl;
    }

    @Override
    public String tentukanKategori() {
        if (kebutuhanAir < 1500) return "Kurang Cukup";
        else if (kebutuhanAir < 2500) return "Cukup";
        else return "Lebih dari Cukup";
    }

    @Override
    public String getHasilLengkap() {
        return String.format("Kebutuhan : %.0f ml (%.2f Liter)", kebutuhanMl, kebutuhanMl / 1000);
    }
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new CekAir().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCek;
    private javax.swing.JButton btnReset;
    private javax.swing.JComboBox<String> comAktivitas;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel lblAktivitas;
    private javax.swing.JLabel lblBerat;
    private javax.swing.JLabel lblHasil;
    private javax.swing.JTextField txtBerat;
    // End of variables declaration//GEN-END:variables
}
