/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

/**
 *
 * @author Hilmi, Faizah, dan Desta
 */
import javax.swing.JOptionPane;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.SQLException;
public class CekBeratBadan extends javax.swing.JFrame implements PerhitunganKesehatan{
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(CekBeratBadan.class.getName());

    /**
     * Creates new form CekBeratBadan
     */
    private double imt;
    private double beratIdeal;
    private String status;
    private String rekomendasi;
    public CekBeratBadan() {
        initComponents();
        setResizable(false);
        setSize(1062, 574);
        setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel2 = new javax.swing.JLabel();
        lblBerat = new javax.swing.JLabel();
        txtBerat = new javax.swing.JTextField();
        lblTinggi = new javax.swing.JLabel();
        txtTinggi = new javax.swing.JTextField();
        btnReset = new javax.swing.JButton();
        btnCek = new javax.swing.JButton();
        lblHasil = new javax.swing.JLabel();
        btnRiwayat = new javax.swing.JButton();
        btnKembali = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setSize(new java.awt.Dimension(1062, 574));
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel2.setFont(new java.awt.Font("SansSerif", 1, 48)); // NOI18N
        jLabel2.setText("Cek Berat Badan Ideal");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 30, -1, -1));

        lblBerat.setBackground(new java.awt.Color(0, 0, 0));
        lblBerat.setFont(new java.awt.Font("SansSerif", 1, 24)); // NOI18N
        lblBerat.setText("Berat Badan (Kg)");
        getContentPane().add(lblBerat, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 170, -1, -1));

        txtBerat.setBackground(new java.awt.Color(204, 255, 255));
        txtBerat.setFont(new java.awt.Font("SansSerif", 0, 18)); // NOI18N
        txtBerat.addActionListener(this::txtBeratActionPerformed);
        getContentPane().add(txtBerat, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 210, 190, 60));

        lblTinggi.setFont(new java.awt.Font("SansSerif", 1, 24)); // NOI18N
        lblTinggi.setText("Tinggi Badan (Cm)");
        getContentPane().add(lblTinggi, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 170, -1, -1));

        txtTinggi.setBackground(new java.awt.Color(255, 255, 204));
        txtTinggi.setFont(new java.awt.Font("SansSerif", 0, 18)); // NOI18N
        txtTinggi.addActionListener(this::txtTinggiActionPerformed);
        getContentPane().add(txtTinggi, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 210, 210, 60));

        btnReset.setBackground(new java.awt.Color(204, 0, 51));
        btnReset.setFont(new java.awt.Font("SansSerif", 1, 16)); // NOI18N
        btnReset.setForeground(new java.awt.Color(255, 255, 255));
        btnReset.setText("Reset");
        btnReset.addActionListener(this::btnResetActionPerformed);
        getContentPane().add(btnReset, new org.netbeans.lib.awtextra.AbsoluteConstraints(740, 180, 150, 40));

        btnCek.setBackground(new java.awt.Color(102, 255, 102));
        btnCek.setFont(new java.awt.Font("SansSerif", 1, 16)); // NOI18N
        btnCek.setForeground(new java.awt.Color(255, 255, 255));
        btnCek.setText("Cek Sekarang");
        btnCek.addActionListener(this::btnCekActionPerformed);
        getContentPane().add(btnCek, new org.netbeans.lib.awtextra.AbsoluteConstraints(740, 230, 150, 40));

        lblHasil.setBackground(new java.awt.Color(204, 255, 204));
        lblHasil.setFont(new java.awt.Font("SansSerif", 0, 24)); // NOI18N
        lblHasil.setForeground(new java.awt.Color(255, 255, 255));
        lblHasil.setOpaque(true);
        getContentPane().add(lblHasil, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 310, 710, 190));

        btnRiwayat.setBackground(new java.awt.Color(153, 0, 153));
        btnRiwayat.setFont(new java.awt.Font("SansSerif", 1, 14)); // NOI18N
        btnRiwayat.setForeground(new java.awt.Color(255, 255, 255));
        btnRiwayat.setText("Riwayat");
        btnRiwayat.addActionListener(this::btnRiwayatActionPerformed);
        getContentPane().add(btnRiwayat, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 480, -1, -1));

        btnKembali.setBackground(new java.awt.Color(204, 0, 204));
        btnKembali.setFont(new java.awt.Font("SansSerif", 1, 14)); // NOI18N
        btnKembali.setForeground(new java.awt.Color(255, 255, 255));
        btnKembali.setText("Beranda");
        btnKembali.addActionListener(this::btnKembaliActionPerformed);
        getContentPane().add(btnKembali, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 440, -1, -1));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/background/bgCekBerat1.png"))); // NOI18N
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1070, 570));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtBeratActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtBeratActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtBeratActionPerformed

    private void btnCekActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCekActionPerformed
        // TODO add your handling code here:
        Connection conn = null;
        PreparedStatement pst = null;

        try {
            double berat = Double.parseDouble(txtBerat.getText().trim());
            double tinggi = Double.parseDouble(txtTinggi.getText().trim());

            if (berat <= 0 || tinggi <= 0) {
                JOptionPane.showMessageDialog(this, "Masukkan angka lebih dari 0!", "Input Salah", JOptionPane.WARNING_MESSAGE);
                return;
            }

            // 1. Hitung IMT
            double tinggiMeter = tinggi / 100;
            imt = berat / (tinggiMeter * tinggiMeter);

            // 2. Berat Ideal Rumus Broca
            beratIdeal = (tinggi - 100) - ((tinggi - 100) * 0.1);

            // 3. Tentukan Status & Rekomendasi
            if (imt < 18.5) {
                status = "Kurus";
                rekomendasi = "Perbanyak asupan gizi dan makan teratur.";
                lblHasil.setBackground(new java.awt.Color(187, 222, 251));
            } else if (imt <= 24.9) {
                status = "Berat Badan Ideal ✅";
                rekomendasi = "Pertahankan pola makan dan gaya hidup sehat.";
                lblHasil.setBackground(new java.awt.Color(200, 230, 201));
            } else if (imt <= 29.9) {
                status = "Kelebihan Berat Badan ⚠️";
                rekomendasi = "Kurangi makanan berlemak dan perbanyak olahraga.";
                lblHasil.setBackground(new java.awt.Color(255, 224, 178));
            } else {
                status = "Obesitas ❌";
                rekomendasi = "Atur pola makan dan rutin berolahraga, konsultasi ke dokter jika perlu.";
                lblHasil.setBackground(new java.awt.Color(255, 205, 210));
            }

            // TAMPILKAN SEMUA DI SATU TEMPAT (lblHasil)
            lblHasil.setText(String.format(
                "<html><b>HASIL PERHITUNGAN</b><br>" +
                "Indeks Massa Tubuh (IMT) : %.2f<br>" +
                "Berat Badan Ideal       : %.1f Kg<br>" +
                "Status Kesehatan        : %s<br>" +
                "Rekomendasi             : %s</html>",
                imt, beratIdeal, status, rekomendasi
            ));
            lblHasil.setOpaque(true);

            // SIMPAN KE DATABASE
            conn = Koneksi.bukaKoneksi();
            String sql = "INSERT INTO riwayat_berat (berat, tinggi, status, berat_ideal, rekomendasi) VALUES (?, ?, ?, ?, ?)";
            pst = conn.prepareStatement(sql);
            pst.setDouble(1, berat);
            pst.setDouble(2, tinggi);
            pst.setString(3, status);
            pst.setDouble(4, beratIdeal);
            pst.setString(5, rekomendasi);

            pst.executeUpdate();
            JOptionPane.showMessageDialog(this, "✅ Data berhasil disimpan!");

        } catch (NumberFormatException e) {
            JOptionPane.showMessageDialog(this, "❌ Masukkan hanya angka yang valid!", "Kesalahan Input", JOptionPane.WARNING_MESSAGE);
        } catch (SQLException e) {
            JOptionPane.showMessageDialog(this, "❌ Gagal simpan: " + e.getMessage(), "Kesalahan Database", JOptionPane.ERROR_MESSAGE);
        } finally {
            try {
                if (pst != null) pst.close();
                if (conn != null) conn.close();
            } catch (SQLException ex) {
                ex.printStackTrace();
            }
        }
    }//GEN-LAST:event_btnCekActionPerformed

    private void btnResetActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnResetActionPerformed
        // TODO add your handling code here:
        txtBerat.setText("");
        txtTinggi.setText("");
        lblHasil.setText("");
        lblHasil.setBackground(new java.awt.Color(204, 255, 204));
        txtBerat.requestFocus();
    }//GEN-LAST:event_btnResetActionPerformed

    private void txtTinggiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtTinggiActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtTinggiActionPerformed

    private void btnRiwayatActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRiwayatActionPerformed
        // TODO add your handling code here:
        new RiwayatCekBB().setVisible(true);
        dispose();
    }//GEN-LAST:event_btnRiwayatActionPerformed

    private void btnKembaliActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnKembaliActionPerformed
        // TODO add your handling code here:
        new Beranda().setVisible(true);
        dispose();
    }//GEN-LAST:event_btnKembaliActionPerformed
    
        @Override
        public double hitungNilai() {
            return imt;
        }

        @Override
        public String tentukanKategori() {
            return status;
        }

        @Override
        public String getHasilLengkap() {
             return String.format("IMT: %.2f | Berat Ideal: %.1fkg | %s", imt, beratIdeal, status);
        }
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new CekBeratBadan().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCek;
    private javax.swing.JButton btnKembali;
    private javax.swing.JButton btnReset;
    private javax.swing.JButton btnRiwayat;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel lblBerat;
    private javax.swing.JLabel lblHasil;
    private javax.swing.JLabel lblTinggi;
    private javax.swing.JTextField txtBerat;
    private javax.swing.JTextField txtTinggi;
    // End of variables declaration//GEN-END:variables
}
