/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

/**
 *
 * @author Hilmi, Faizah, dan Desta
 */
import javax.swing.JOptionPane;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
public class RegisterForm extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(RegisterForm.class.getName());

    /**
     * Creates new form RegisterForm
     */
    public RegisterForm() {
        initComponents();
        setResizable(false);
        setSize(1062, 574); 
        setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblEmail = new javax.swing.JLabel();
        txtEmail = new javax.swing.JTextField();
        lblKataSandi = new javax.swing.JLabel();
        btnRegis = new javax.swing.JButton();
        chkTampilkanSandi = new javax.swing.JCheckBox();
        txtKataSandi = new javax.swing.JPasswordField();
        jButton1 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBounds(new java.awt.Rectangle(0, 0, 0, 0));
        setMaximumSize(new java.awt.Dimension(1062, 574));
        setMinimumSize(new java.awt.Dimension(1062, 574));
        setPreferredSize(new java.awt.Dimension(1062, 574));
        setResizable(false);
        setSize(new java.awt.Dimension(1062, 574));
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lblEmail.setFont(new java.awt.Font("SansSerif", 1, 24)); // NOI18N
        lblEmail.setForeground(new java.awt.Color(255, 255, 255));
        lblEmail.setText("Email");
        getContentPane().add(lblEmail, new org.netbeans.lib.awtextra.AbsoluteConstraints(720, 190, 80, 50));

        txtEmail.setFont(new java.awt.Font("SansSerif", 0, 14)); // NOI18N
        txtEmail.addActionListener(this::txtEmailActionPerformed);
        getContentPane().add(txtEmail, new org.netbeans.lib.awtextra.AbsoluteConstraints(720, 240, 260, 40));

        lblKataSandi.setFont(new java.awt.Font("SansSerif", 1, 24)); // NOI18N
        lblKataSandi.setForeground(new java.awt.Color(255, 255, 255));
        lblKataSandi.setText("Kata Sandi");
        getContentPane().add(lblKataSandi, new org.netbeans.lib.awtextra.AbsoluteConstraints(720, 290, -1, -1));

        btnRegis.setFont(new java.awt.Font("SansSerif", 1, 14)); // NOI18N
        btnRegis.setForeground(new java.awt.Color(0, 0, 204));
        btnRegis.setText("Register");
        btnRegis.addActionListener(this::btnRegisActionPerformed);
        getContentPane().add(btnRegis, new org.netbeans.lib.awtextra.AbsoluteConstraints(720, 420, 260, 40));

        chkTampilkanSandi.setFont(new java.awt.Font("SansSerif", 1, 14)); // NOI18N
        chkTampilkanSandi.setForeground(new java.awt.Color(255, 255, 255));
        chkTampilkanSandi.setText("Tampilkan Kata Sandi");
        chkTampilkanSandi.addActionListener(this::chkTampilkanSandiActionPerformed);
        getContentPane().add(chkTampilkanSandi, new org.netbeans.lib.awtextra.AbsoluteConstraints(720, 380, 220, -1));

        txtKataSandi.setFont(new java.awt.Font("SansSerif", 0, 14)); // NOI18N
        getContentPane().add(txtKataSandi, new org.netbeans.lib.awtextra.AbsoluteConstraints(720, 330, 260, 40));

        jButton1.setFont(new java.awt.Font("SansSerif", 1, 14)); // NOI18N
        jButton1.setForeground(new java.awt.Color(255, 255, 255));
        jButton1.setText("Sudah punya akun? Login di sini");
        jButton1.setBorderPainted(false);
        jButton1.setContentAreaFilled(false);
        jButton1.addActionListener(this::jButton1ActionPerformed);
        getContentPane().add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(720, 470, -1, -1));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/background/bgRegis.png"))); // NOI18N
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1060, 580));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtEmailActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtEmailActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtEmailActionPerformed

    private void btnRegisActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRegisActionPerformed
        // TODO add your handling code here:
        String email = txtEmail.getText().trim();
        String sandi = new String(txtKataSandi.getPassword());
         // Validasi tidak boleh kosong
         if (email.isEmpty() || sandi.isEmpty()) {
             JOptionPane.showMessageDialog(this, "Email dan Kata Sandi tidak boleh kosong!", "Peringatan", JOptionPane.WARNING_MESSAGE);
             return;
         }
         // Validasi format email sederhana
         if (!email.contains("@") || !email.contains(".")) {
             JOptionPane.showMessageDialog(this, "Masukkan alamat email yang valid!", "Peringatan", JOptionPane.WARNING_MESSAGE);
             return;
         }
         // Simpan ke database
         try {
             Connection conn = Koneksi.bukaKoneksi();
             if (conn == null) {
                 JOptionPane.showMessageDialog(this, "Koneksi database gagal!", "Error", JOptionPane.ERROR_MESSAGE);
                 return;
             }
             // Cek apakah email sudah terdaftar
             String cekEmail = "SELECT * FROM pengguna WHERE email = ?";
             PreparedStatement psCek = conn.prepareStatement(cekEmail);
             psCek.setString(1, email);
             if (psCek.executeQuery().next()) {
                 JOptionPane.showMessageDialog(this, "Email sudah digunakan! Gunakan email lain.", "Gagal", JOptionPane.WARNING_MESSAGE);
                 return;
             }
             // Simpan data baru
             String sql = "INSERT INTO pengguna (email, kata_sandi) VALUES (?, ?)";
             PreparedStatement ps = conn.prepareStatement(sql);
             ps.setString(1, email);
             ps.setString(2, sandi);
             ps.executeUpdate();
             JOptionPane.showMessageDialog(this, "Registrasi Berhasil! Silakan login.");
             // Buka halaman Login
             new LoginForm().setVisible(true);
             this.dispose();
         } catch (SQLException e) {
             JOptionPane.showMessageDialog(this, "Error: " + e.getMessage(), "Kesalahan", JOptionPane.ERROR_MESSAGE);
         }
    }//GEN-LAST:event_btnRegisActionPerformed

    private void chkTampilkanSandiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_chkTampilkanSandiActionPerformed
        // TODO add your handling code here:
        if (chkTampilkanSandi.isSelected()) {
             txtKataSandi.setEchoChar((char)0);
         } else {
             txtKataSandi.setEchoChar('*');
         }
    }//GEN-LAST:event_chkTampilkanSandiActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        new LoginForm().setVisible(true);
        this.dispose();
    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new RegisterForm().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnRegis;
    private javax.swing.JCheckBox chkTampilkanSandi;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel lblEmail;
    private javax.swing.JLabel lblKataSandi;
    private javax.swing.JTextField txtEmail;
    private javax.swing.JPasswordField txtKataSandi;
    // End of variables declaration//GEN-END:variables
}
